name = "ilap/bls"
version = "0.4.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken library implementing high level BLS12-381 cryptographic operations."

[repository]
user = "ilap"
project = "bls"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"
